(() => {
'use strict';
const RELEASE='20260915.1', KEY='owner-cart-v1', LOCALES={ko:'ko-KR',en:'en-US',ja:'ja-JP',zh:'zh-CN',tw:'zh-TW',id:'id-ID',hi:'hi-IN'};
const aliases={'zh-TW':'tw','zh-tw':'tw','zh-Hant':'tw','zh-CN':'zh','zh-cn':'zh','zh-Hans':'zh','jp':'ja','in':'hi','id-ID':'id','hi-IN':'hi'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readStorage(key){try{return localStorage.getItem(key)}catch{return null}}
let lang=new URLSearchParams(location.search).get('lang')||readStorage('owner-language')||'ko';lang=aliases[lang]||lang;if(!LOCALES[lang])lang='ko';
let cart=[],filter='all',current=null,lastAnswer='',recognition=null,loop=false,speaking=false,restartTimer=null,toastTimer=null,permissionPending=false,session=0;
const names=(ko,en,ja,zh,tw,id,hi)=>({ko,en,ja,zh,tw,id,hi});
const products=[
{id:'cream',category:'beauty',photo:0,model:'SENOID',retail:99000,member:61000,mv:22180,options:['50 ml'],name:names('세노이드 네오 다이아크림','SENOID Neo Dia Cream','SENOID ネオダイアクリーム','SENOID Neo Dia 面霜','SENOID Neo Dia 乳霜','Krim SENOID Neo Dia','SENOID Neo Dia क्रीम')},
{id:'essence',category:'beauty',photo:1,model:'SENOID',retail:67500,member:45000,mv:16360,options:['50 ml'],name:names('세노이드 다이아 퍼밍 에센스','SENOID Dia Firming Essence','SENOID ダイアファーミングエッセンス','SENOID Dia 紧致精华','SENOID Dia 緊緻精華','Esens Pengencang SENOID Dia','SENOID Dia फर्मिंग एसेंस')},
{id:'mist',category:'beauty',photo:2,model:'SENOID',retail:64500,member:43000,mv:15630,options:['100 ml'],name:names('세노이드 루미너스 샤인 미스트','SENOID Luminous Shine Mist','SENOID ルミナスシャインミスト','SENOID 亮泽喷雾','SENOID 亮澤噴霧','Mist SENOID Luminous Shine','SENOID Luminous Shine मिस्ट')},
{id:'exonia',category:'beauty',photo:3,model:'EXONIA 33',retail:550000,member:330000,mv:120000,options:[],name:names('엑소니아 33앰플','EXONIA 33 Ampoule','EXONIA 33アンプル','EXONIA 33安瓶','EXONIA 33安瓶','Ampul EXONIA 33','EXONIA 33 ऐम्पूल')},
{id:'airjet',category:'beauty',photo:4,model:'Cosmetic Airjet',retail:273000,member:270000,mv:81000,options:[],name:names('코스메틱 에어젯','Cosmetic Airjet','コスメティック エアジェット','Cosmetic Airjet 美容喷雾设备','Cosmetic Airjet 美容噴霧設備','Cosmetic Airjet','Cosmetic Airjet')},
{id:'secret',category:'device',photo:9,model:'SECRET POWER',retail:1920000,member:1360000,mv:450000,options:['M','L'],name:names('시크릿 파워(온열)','Secret Power (Heated)','シークレットパワー（温熱）','Secret Power（温热）','Secret Power（溫熱）','Secret Power (Pemanas)','Secret Power (हीटेड)')},
{id:'dugeuni',category:'device',photo:7,model:'DUGEUNI',retail:1680000,member:1100000,mv:400000,options:[],name:names('두근이','Dugeuni','ドゥグニ','Dugeuni（두근이）','Dugeuni（두근이）','Dugeuni','Dugeuni')},
{id:'hairon',category:'device',photo:8,model:'HAIRON',retail:660000,member:550000,mv:200000,options:[],name:names('헤어온','Hairon','ヘアオン','Hairon','Hairon','Hairon','Hairon')}
];
const lineup=[['701','트라이앵글','Triangle',1,10],['702','서포터','Supporter',1,11],['703','컴포터','Comforter',1,12],['801','액티브','Active',2,13],['802','다이나믹','Dynamic',2,14],['803','액티런','Actirun',2,6,70000,25000,'XS 225–235 mm'],['901','메디칼','Medical',3,5,140000,50000,'XL 285–295 mm'],['902','오소틱','Orthotic',3,17],['903','메디워크','Mediwalk',3,18]];
for(const [code,ko,en,stage,photo,price,mv,size] of lineup)products.push({id:`dfh${code}`,category:'insole',photo,model:`DFH${code}`,stage,retail:price??null,member:price??null,mv:mv??null,options:size?[size]:[],name:names(`닥터풋헬스 ${ko}`,`Dr. Foothealth ${en}`,`Dr. Foothealth ${en} インソール`,`Dr. Foothealth ${en} 鞋垫`,`Dr. Foothealth ${en} 鞋墊`,`Insole Dr. Foothealth ${en}`,`Dr. Foothealth ${en} इनसोल`)});
const byId=new Map(products.map(p=>[p.id,p]));
const t=k=>window.OWNER_I18N[lang][k]??window.OWNER_I18N.en[k]??k;
const title=p=>p.name[lang];
const money=n=>`KRW ${new Intl.NumberFormat(LOCALES[lang],{maximumFractionDigits:0}).format(n)}`;
const number=n=>new Intl.NumberFormat(LOCALES[lang]).format(n);
function photo(p,extra=''){return `<div class="product-photo ${extra}" role="img" aria-label="${esc(title(p))}" style="--col:${p.photo%5};--row:${Math.floor(p.photo/5)}"></div>`}
function prices(p){if(p.retail==null)return `<p class="micro">${esc(t('priceUnknown'))}</p>`;return `<div class="prices"><span>${esc(t('retail'))}</span><b>${money(p.retail)}</b><span>${esc(t('member'))}</span><b class="member">${money(p.member)}</b><span>MV</span><b class="mv">${number(p.mv)}</b></div>`}
function notify(key){$('#toast').textContent=t(key);clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',3500)}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(cart))}catch{notify('saveFailed')}$('#cartCount').textContent=cart.reduce((s,c)=>s+c.qty,0)}
try{const raw=JSON.parse(readStorage(KEY)||'[]');if(Array.isArray(raw))cart=raw.filter(c=>c&&byId.get(c.id)?.retail!=null&&Number.isInteger(c.qty)&&c.qty>0&&c.qty<=99&&typeof c.option==='string'&&(byId.get(c.id).options.length?byId.get(c.id).options.includes(c.option):c.option==='')).slice(0,40);const unique=new Map();for(const c of cart){const key=c.id+'|'+c.option;const old=unique.get(key);if(old)old.qty=Math.min(99,old.qty+c.qty);else unique.set(key,{id:c.id,qty:c.qty,option:c.option})}cart=[...unique.values()]}catch{cart=[]}
function applyLanguage(next){stopVoice();lang=aliases[next]||next;if(!LOCALES[lang])lang='ko';document.documentElement.lang=LOCALES[lang];document.documentElement.dataset.lang=lang;$('#language').value=lang;$$('[data-t]').forEach(el=>{if(el.dataset.t==='hero')el.innerHTML=t('hero');else el.textContent=t(el.dataset.t)});$$('[data-placeholder]').forEach(el=>{el.placeholder=t(el.dataset.placeholder);el.setAttribute('aria-label',t(el.dataset.placeholder))});$$('[data-close]').forEach(el=>el.setAttribute('aria-label',t('close')));$('#researchLink').href=`research.html?lang=${['ko','en','ja','zh'].includes(lang)?lang:'en'}`;try{localStorage.setItem('owner-language',lang)}catch{}const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u.pathname+u.search+u.hash);try{const dn=new Intl.DisplayNames([LOCALES[lang]],{type:'region'});[...$('#country').options].forEach(o=>{if(o.value!=='OTHER')o.textContent=dn.of(o.value)})}catch{}renderProducts();renderCart();if($('#productDialog').open&&current)showProduct(current.id,false);$('#messages').replaceChildren();lastAnswer='';if($('#assistantDialog').open)addMessage(t('greeting'),'bot');}
function renderProducts(){const q=$('#search').value.trim().toLocaleLowerCase();const items=products.filter(p=>(filter==='all'||p.category===filter)&&(!q||[p.id,p.model,...Object.values(p.name),...p.options].join(' ').toLocaleLowerCase().includes(q)));$('#empty').hidden=!!items.length;$('#productGrid').innerHTML=items.map(p=>`<article class="card" data-product="${p.id}"><button class="photo-btn" data-detail="${p.id}" aria-label="${esc(title(p))}">${photo(p)}<span class="category">${esc(t(p.category))}${p.stage?' · '+t('stage')+' '+p.stage:''}</span></button><div class="card-body"><h3>${esc(title(p))}</h3><div class="model">${esc(p.model)}</div>${prices(p)}<div class="card-buttons"><button class="outline" data-detail="${p.id}">${esc(t('details'))}</button><button class="primary" data-add="${p.id}" ${p.retail==null?'disabled':''}>${esc(t('add'))}</button></div></div></article>`).join('');}
function showProduct(id,open=true){const p=byId.get(id);if(!p)return;current=p;const options=p.options.length?`<label>${esc(t('size'))}<select id="productOption">${p.options.map(o=>`<option>${esc(o)}</option>`).join('')}</select></label>`:(p.category==='insole'?esc(t('unknownSize')):'');$('#productDetail').innerHTML=`<div class="detail-grid">${photo(p)}<div><span class="eyebrow">${esc(p.model)}</span><h2>${esc(title(p))}</h2>${prices(p)}<div class="detail-meta">${p.stage?`${esc(t('stage'))} ${p.stage}<br>`:''}${options}</div><p class="micro">${esc(t('priceNote'))}</p><div class="detail-actions"><button class="primary" data-detail-add="${p.id}" ${p.retail==null?'disabled':''}>${esc(t('add'))}</button><button class="outline" data-ask="${p.id}">${esc(t('askProduct'))}</button><button class="outline" data-poster="${p.id}">${esc(t('photoSave'))}</button></div></div></div><p class="micro">${esc(t('medicalNote'))}</p>`;if(open&&!$('#productDialog').open)$('#productDialog').showModal();}
function addCart(id,option){const p=byId.get(id);if(!p||p.retail==null){notify('pendingLine');return}if(p.options.length>1&&!option){showProduct(id);return}option=option??p.options[0]??'';if(p.options.length&&!p.options.includes(option))return;const line=cart.find(c=>c.id===id&&c.option===option);if(line){if(line.qty>=99){notify('limit');return}line.qty++}else cart.push({id,option,qty:1});persist();renderCart();notify('added')}
function renderCart(){const total=cart.reduce((s,c)=>s+byId.get(c.id).retail*c.qty,0);$('#cartLines').innerHTML=cart.length?cart.map((c,i)=>{const p=byId.get(c.id);return `<div class="cart-line">${photo(p)}<div><h3>${esc(title(p))}</h3><small>${esc(c.option||p.model)} · ${money(p.retail*c.qty)}</small><div class="qty"><button data-qty="${i}" data-delta="-1" aria-label="-1">−</button><span>${c.qty}</span><button data-qty="${i}" data-delta="1" aria-label="+1">+</button></div></div><button class="remove" data-remove="${i}" aria-label="${esc(t('removed'))}">×</button></div>`}).join(''):`<p class="micro">${esc(t('emptyCart'))}</p>`;$('#cartTotal').textContent=money(total);$('#cartCount').textContent=cart.reduce((s,c)=>s+c.qty,0);$('#draftSave').disabled=!cart.length;}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),30000)}
function saveDraft(){if(!cart.length)return;const total=cart.reduce((s,c)=>s+byId.get(c.id).retail*c.qty,0);const out=['GLOBAL OWNER',t('draftNote'),new Date().toISOString(),`${t('country')}: ${$('#country').selectedOptions[0].textContent}`,'',...cart.map(c=>`${title(byId.get(c.id))} / ${c.option||byId.get(c.id).model} / ${t('unit')}: ${c.qty} / ${money(byId.get(c.id).retail*c.qty)}`),'',`${t('subtotal')}: ${money(total)}`,t('shippingPending'),t('localOnly')];download(new Blob(['\uFEFF'+out.join('\n')],{type:'text/plain;charset=utf-8'}),`OWNER-draft-${lang}-${Date.now()}.txt`);notify('downloaded')}
const sprite=new Image();sprite.src='upgrade/product-photos.webp';sprite.onerror=()=>notify('dataError');
async function savePoster(id){const p=byId.get(id);try{await sprite.decode();const cv=document.createElement('canvas');cv.width=900;cv.height=1260;const x=cv.getContext('2d');x.fillStyle='#f2eee4';x.fillRect(0,0,900,1260);x.fillStyle='#176859';x.font='500 25px sans-serif';x.fillText('GLOBAL OWNER × REVERSE12',65,65);const sw=sprite.naturalWidth/5,sh=sprite.naturalHeight/4;x.drawImage(sprite,(p.photo%5)*sw,Math.floor(p.photo/5)*sh,sw,sh,200,115,500,555);x.fillStyle='#303a36';x.font='500 31px sans-serif';let y=730;let row='';for(const char of title(p)){if(x.measureText(row+char).width>770&&row){x.fillText(row,65,y);y+=45;row=''}row+=char}x.fillText(row,65,y);y+=50;x.font='23px sans-serif';x.fillStyle='#667367';x.fillText(p.model+(p.options.length?' · '+p.options.join(' / '):''),65,y);y+=55;const lines=p.retail==null?[t('priceUnknown')]:[`${t('retail')}   ${money(p.retail)}`,`${t('member')}   ${money(p.member)}`,`MV   ${number(p.mv)}`];x.font='27px sans-serif';for(const [i,line] of lines.entries()){x.fillStyle=i===1?'#176859':'#303a36';x.fillText(line,65,y);y+=48}x.font='18px sans-serif';x.fillStyle='#697166';let fy=1120,frow='';for(const char of t('priceNote')){if(x.measureText(frow+char).width>760&&frow){x.fillText(frow,65,fy);fy+=27;frow=''}frow+=char}x.fillText(frow,65,fy);cv.toBlob(b=>{if(b)download(b,`OWNER-${p.id}-${lang}.png`);else notify('shareError')},'image/png')}catch{notify('shareError')}}
function addMessage(text,role){const el=document.createElement('div');el.className='message '+role;el.textContent=text;$('#messages').appendChild(el);while($('#messages').children.length>30)$('#messages').firstElementChild.remove();$('#messages').scrollTop=$('#messages').scrollHeight;if(role==='bot')lastAnswer=text}
function openHelp(){if($('#productDialog').open)$('#productDialog').close();if($('#cartDialog').open)$('#cartDialog').close();if(!$('#assistantDialog').open)$('#assistantDialog').showModal();if(!$('#messages').childElementCount)addMessage(t('greeting'),'bot')}
const normalize=s=>s.toLowerCase().normalize('NFKC').replace(/[\s·–_()-]/g,'');
function findProduct(q){const n=normalize(q);const short={cream:['크림','cream','クリーム','面霜','乳霜','krim','क्रीम'],essence:['에센스','essence','エッセンス','精华','精華','esens','एसेंस'],mist:['미스트','mist','ミスト','喷雾','噴霧','मिस्ट'],secret:['시크릿파워','secretpower','シークレットパワー'],dfh803:['액티런','actirun'],dfh901:['메디칼','medical']};let best=null,score=0;for(const p of products){const terms=[p.id,...Object.values(p.name),...(p.model!=='SENOID'?[p.model]:[]),...(p.id.startsWith('dfh')?[p.name.ko.split(' ').pop()]:[]),...(short[p.id]||[])];for(const term of terms){const v=normalize(term);if(v.length>=2&&n.includes(v)&&v.length>score){score=v.length;best=p}}}return best}
function answer(q,voice=false){if(!q.trim())return;addMessage(q,'user');let p=findProduct(q);if(p)current=p;else p=current;let a='';const unknown=/치료|통증|키성장|키가|효능|부작용|재고|배송|반품|주문조회|사용법|treat|pain|height|effect|stock|ship|deliver|return|refund|tracking|how to use|効果|痛み|治療|配送|使い方|使用|功效|療效|治疗|增高|退货|退貨|订单|訂單|运费|運費|pengiriman|khasiat|stok|retur|cara pakai|इलाज|दर्द|प्रभाव|शिपिंग|वापसी|इस्तेमाल/i;
if(unknown.test(q)){a=t('unverified')}else if(/장바구니|カート|购物车|購物車|cart|keranjang|कार्ट/i.test(q)&&!/담|추가|add|加入|入れ|tambahkan|जोड़/i.test(q)){$('#assistantDialog').close();$('#cartDialog').showModal();a=t('localOnly')}else if(!p){a=t('chooseProduct')}else if(/담아|담기|추가|구매할|add|加入|入れ|tambahkan|जोड़/i.test(q)){if(p.retail==null)a=t('pendingLine');else if(p.options.length>1){$('#assistantDialog').close();showProduct(p.id);a=t('size')+': '+p.options.join(' / ')}else{addCart(p.id);a=t('added')+' · '+title(p)}}else{a=title(p)+'\n'+(p.retail==null?t('priceUnknown'):`${t('retail')}: ${money(p.retail)}\n${t('member')}: ${money(p.member)}\nMV: ${number(p.mv)}`)+(p.options.length?`\n${t('size')}: ${p.options.join(' / ')}`:p.category==='insole'?`\n${t('unknownSize')}`:'')+'\n'+t('priceNote')}
addMessage(a,'bot');if((voice||loop)&&$('#assistantDialog').open)speak(a);return a}
function voiceStatus(key){$('#voiceStatus').textContent=t(key)}
function stopVoice(){session++;loop=false;speaking=false;permissionPending=false;clearTimeout(restartTimer);restartTimer=null;$('#continuous').checked=false;const r=recognition;recognition=null;if(r)try{r.abort()}catch{}if('speechSynthesis'in window)window.speechSynthesis.cancel();voiceStatus('voiceStopped')}
function resume(){clearTimeout(restartTimer);if(loop&&!speaking&&!recognition&&!permissionPending&&$('#assistantDialog').open)restartTimer=setTimeout(()=>startRecognition(false),700)}
function speak(text){if(!('speechSynthesis'in window)){voiceStatus('noVoice');loop=false;$('#continuous').checked=false;return}const voices=window.speechSynthesis.getVoices();const locale=LOCALES[lang].toLowerCase();const voice=voices.find(v=>v.lang.toLowerCase()===locale)||voices.find(v=>v.lang.toLowerCase().split('-')[0]===locale.split('-')[0]);if(!voice){voiceStatus('noVoice');resume();return}const r=recognition;recognition=null;if(r)try{r.abort()}catch{}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=LOCALES[lang];u.voice=voice;u.rate=.98;u.volume=1;speaking=true;const s=session;u.onend=()=>{if(s!==session)return;speaking=false;voiceStatus('ready');resume()};u.onerror=()=>{if(s!==session)return;speaking=false;voiceStatus('micError');loop=false;$('#continuous').checked=false};window.speechSynthesis.speak(u)}
async function startRecognition(requestPermission=true){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){voiceStatus('noMic');return}if(permissionPending)return;const s=session;if(requestPermission){if(recognition){stopVoice();return}if('speechSynthesis'in window)window.speechSynthesis.cancel();speaking=false;permissionPending=true;try{if(navigator.mediaDevices?.getUserMedia){const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(track=>track.stop())}if(s!==session||!$('#assistantDialog').open)return;loop=$('#continuous').checked}catch{loop=false;$('#continuous').checked=false;voiceStatus('micDenied');return}finally{permissionPending=false}}
if(s!==session||!$('#assistantDialog').open||recognition||speaking)return;const r=new SR();recognition=r;r.lang=LOCALES[lang];r.continuous=false;r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>{if(s===session)voiceStatus('listening')};r.onresult=ev=>{if(s!==session)return;const text=ev.results[0][0].transcript;answer(text,true)};r.onerror=ev=>{if(s!==session)return;if(ev.error==='aborted')return;if(ev.error==='no-speech'){voiceStatus('ready');return}loop=false;$('#continuous').checked=false;voiceStatus(ev.error==='not-allowed'||ev.error==='service-not-allowed'?'micDenied':'micError')};r.onend=()=>{if(recognition===r)recognition=null;if(s===session)resume()};try{r.start()}catch{recognition=null;loop=false;$('#continuous').checked=false;voiceStatus('micError')}}
$('#language').addEventListener('change',e=>applyLanguage(e.target.value));$('#search').addEventListener('input',renderProducts);$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderProducts()}));
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close){$('#'+b.dataset.close).close();return}if(b.dataset.detail)showProduct(b.dataset.detail);if(b.dataset.add)addCart(b.dataset.add);if(b.dataset.detailAdd)addCart(b.dataset.detailAdd,$('#productOption')?.value);if(b.dataset.ask){current=byId.get(b.dataset.ask);openHelp();answer(title(current))}if(b.dataset.poster)savePoster(b.dataset.poster);if(b.dataset.qty!=null){const c=cart[Number(b.dataset.qty)];if(!c)return;const next=c.qty+Number(b.dataset.delta);if(next>99){notify('limit');return}if(next<=0)cart.splice(Number(b.dataset.qty),1);else c.qty=next;persist();renderCart()}if(b.dataset.remove!=null){cart.splice(Number(b.dataset.remove),1);persist();renderCart();notify('removed')}});
$('#cartOpen').addEventListener('click',()=>{$('#cartDialog').showModal();renderCart()});$('#draftSave').addEventListener('click',saveDraft);$('#assistantOpen').addEventListener('click',openHelp);$('#heroHelp').addEventListener('click',openHelp);$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#question').value.trim();if(q){$('#question').value='';answer(q)}});$('#mic').addEventListener('click',()=>startRecognition(true));$('#speakLast').addEventListener('click',()=>speak(lastAnswer||t('greeting')));$('#stopVoice').addEventListener('click',stopVoice);$('#continuous').addEventListener('change',e=>{if(!e.target.checked){loop=false;clearTimeout(restartTimer)}});$('#assistantDialog').addEventListener('close',stopVoice);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopVoice()});window.addEventListener('pagehide',stopVoice);
let drag=null;const dock=$('#assistantDock'),handle=$('#dragHandle');handle.addEventListener('pointerdown',e=>{const r=dock.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left,top:r.top};handle.setPointerCapture(e.pointerId)});handle.addEventListener('pointermove',e=>{if(!drag)return;const left=Math.max(8,Math.min(innerWidth-dock.offsetWidth-8,drag.left+e.clientX-drag.x)),top=Math.max(8,Math.min(innerHeight-dock.offsetHeight-8,drag.top+e.clientY-drag.y));dock.style.left=left+'px';dock.style.top=top+'px';dock.style.right='auto';dock.style.bottom='auto'});for(const ev of ['pointerup','pointercancel','lostpointercapture'])handle.addEventListener(ev,()=>drag=null);window.addEventListener('resize',()=>{if(dock.style.left){dock.style.left=Math.max(8,Math.min(parseFloat(dock.style.left),innerWidth-dock.offsetWidth-8))+'px';dock.style.top=Math.max(8,Math.min(parseFloat(dock.style.top),innerHeight-dock.offsetHeight-8))+'px'}});
window.addEventListener('storage',e=>{if(e.key===KEY)location.reload()});applyLanguage(lang);renderCart();
// Read-only diagnostics: no customer data or secrets.
window.OWNER_STORE=Object.freeze({release:RELEASE,products:products.map(p=>Object.freeze({...p})),languages:Object.keys(LOCALES),getStatus:()=>({paymentConnected:false,aiConnected:false,ordersSubmitted:false,language:lang})});
})();
